# Generated by Django 3.2 on 2023-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230414_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='desctiption',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
