# Generated by Django 3.2 on 2023-04-19 11:54

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(on_delete=models.SET(reviews.models.get_deleted_genre), to='reviews.genre', verbose_name='Жанр'),
        ),
    ]
